services:
  whatsapp-bot:
    image: openwa/wa-automate:latest
    container_name: whatsapp-bot
    environment:
      WEBHOOK_URL: http://translator:8000/wa/webhook
      WEBHOOK_ENABLED: "true"
      WEBHOOK_ALLOWED_EVENTS: "all"
      FORCE_UPDATE_CW_WEBHOOK: "true"
    command: ["--host","0.0.0.0",
          "--webhook","http://translator:8000/wa/webhook",
          "--skip-url-check",
          "--socket",
          "--popup",
          "--pre-auth-docs"]
    networks: [stack_appnet]
    ports:
      - "0.0.0.0:9001:8002"
    restart: unless-stopped

  translator:
    build: ./translator
    container_name: wa-translator
    environment:
      TZ: Africa/Cairo
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      OPENAI_MODEL: gpt-4o-mini
      WA_BRIDGE: OPENWA
      WA_API_BASE: http://whatsapp-bot:8002
      OWNER_CHAT_ID: "YOUR_NUMBER@c.us"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - ./translator/data:/app/data
    networks: [stack_appnet]
    restart: unless-stopped
    # optional for host testing:
    # ports: ["8000:8000"]

networks:
  stack_appnet:
    external: true
